### PR TITLE
Add fastlane data structures for simplestopwatch.

### PR DESCRIPTION
**Pull request by hayalci**
The fastlane data is used by http://fastlane.tools/ as well as fdroid
(https://gitlab.com/snippets/1895688)
This allows easy extraction of app description, and provides a nice
place for screenshots.

With some extra setup, fastlane can be used to automate Play Store
uploads.

### CODE REVIEW

**Comment by arpruss** [comment]
Sorry, I really don't want to try to figure out how to use this.

**Comment by FestplattenSchnitzel** [comment]
@arpruss you don't have to "use" it. You can leave this directory in your repository, and `Summary` and `Description` at F-Droid will be fine, even if you never adjust it again.

**Comment by IzzySoft** [comment]
Just merging this would leave **you** in control of summary & description, even enabling you to easily add screenshots and more if you like (the latter are purely optional of course). So whenever you want to change how your app is described, you don't need to beg someone else to apply a change but can simply adjust `full_description.txt` accordingly – and the change would be picked up automatically with the next release. A typical win-win, saving both sides precious time. Just ignore the Fastlane "tool" if you don't want it – for F-Droid that's not needed, we only care about the files.

**Comment by arpruss** [comment]
Oh, is the app already on F-Droid?

**Comment by hayalci** [comment]
It will be published once https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8728/ is merged and processed on the server.

The fdroid devs want to keep as little metadata as possible about the app in the fdroid repo, as that can deviate from project author's data very quickly.

Adding these text files  here keep the information on fdroid minimal, while allowing you to change them completely on your own, add new screenshots if you see fit, etc.

There's also the possibility of using the existing fastlane files to make it easier for you to upload to the PlayStore, but as @FestplattenSchnitzel said, it's 100% optional and up to you if you want to use those tools or not.

**Comment by IzzySoft** [comment]
@arpruss so any chance you'll accept this PR so we can include your app with F-Droid? All it's waiting for is your decision. Your app could already have been listed weeks ago :wink:

**Comment by IzzySoft** [comment]
Thanks a lot! As soon as the next tag is available, we'll process the MR at F-Droid then \o/ @hayalci will hopefully follow that up and drop us a note.

**Pull request merged**
